### ISSUE TITLE
Snopes parser is failing

### ISSUE THREAD

**Issue by wybiral** [wybiral/firehose#9]
Looks like they changed their markup a bit. Need to make the parser more generic/fault tolerant.

```python
Traceback (most recent call last):
  File "firehose\sources\__init__.py", line 14, in run
    await self.update(db, queue)
  File "firehose\sources\snopes.py", line 22, in update
    articles = div.find_all('article', {'class': 'media-wrapper'})
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Comment by wybiral** [comment]
Fixed: 5702320445136bccd4ad36dee77eb02e28b7f286
